---
title: "Modelos"
author: "Julio Iturra - jciturra@uc.cl"
date: "17 de enero de 2019"
output:
  pdf_document: default
header-includes:
  - \usepackage{booktabs}
  - \usepackage{dcolumn}
  - \usepackage{float} #fijar tabla
editor_options: 
  chunk_output_type: console
---

```{r library, message=FALSE, warning=FALSE}
options(scipen=999)
library(dplyr)
library(car)
library(ggplot2)
library(gridExtra)
library(knitr)
library(RItools) #xBalance
library(texreg)
library(lavaan)
library(sjPlot)
library(psych)
library(corrplot) 
library(here)
library(estimatr)

```

```{r datos, message=FALSE, warning=FALSE, include=FALSE}
rm(list=ls())
load("trump2019.Rdata")
# st <- st %>% na.omit
st$jus2 <- (st$JW2+st$JW3+st$JW4+st$JW4)/4 #BJW scale
st$zlog <- as.numeric(scale(st$log_reco_OG))
```

<!-- P40,# Sexo del entrevistado 1= hombre 2 = mujer -->
<!-- P41,# Edad del entrevistado -->
<!-- P45,# Estado civil -->
<!-- P44,# Nivel educacional -->
<!-- P49,# Rango de ingreso total mensual del hogar -->
<!-- P3,#Posición política -->


```{r subset-treatment-groups, message=FALSE, warning=FALSE, include=FALSE, results='asis'}
#Subset según variable TIPO2 full muestra
# st <- st %>% filter(reco < 200) #filtrar anterior < 200 para dejar la base sin datos extremos (superiores)
tpab2 <- st %>% filter(TIPO2==1 | TIPO2==2) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==1 & 2 | A vs B
tpac2 <- st %>% filter(TIPO2==1 | TIPO2==3) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==1 & 3 | A vs C
tpad2 <- st %>% filter(TIPO2==1 | TIPO2==4) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==1 & 3 | A vs D
tpbc2 <- st %>% filter(TIPO2==2 | TIPO2==3) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==1 & 3 | B vs C
tpbd2 <- st %>% filter(TIPO2==2 | TIPO2==4) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==1 & 3 | B vs D
tpcd2 <- st %>% filter(TIPO2==3 | TIPO2==4) %>% select(TIPO2,P40,P41,educ,jus2,ppol,log_perc_OG,log_reco,pdesi,log_reco_OG,reco_OG,zlog) %>% na.omit()  #Subset según TIPO==3 & 4 | C vs D

# tpab2$TIPO2 <- recode(tpab2$TIPO2,"2=0;1=1")  #Recode tratamiento y control: Condción A y Control B| para comparar tratamientos
# tpac2$TIPO2 <- recode(tpac2$TIPO2,"3=0;1=1")  #Recode tratamiento y control: Condción A y Control C| para comparar tratamientos
# tpbc2$TIPO2 <- recode(tpbc2$TIPO2,"2=0;3=1")  #Recode tratamiento y control: Condción C y Control B| para comparar tratamientos

tpad2$TIPO2 <- recode(tpad2$TIPO2,"4=0;1=1") #Recode tratamiento y control: Condción A y Control D| para testear tratamiento
tpbd2$TIPO2 <- recode(tpbd2$TIPO2,"4=0;2=1") #Recode tratamiento y control: Condción B y Control D| para testear tratamiento
tpcd2$TIPO2 <- recode(tpcd2$TIPO2,"4=0;3=1") #Recode tratamiento y control: Condción C y Control D| para testear tratamiento

st$treat <- relevel(factor(st$TIPO2), ref = 4)
```

```{r balance}
bal1 <- lm(TIPO2~factor(P40)+P41+educ+jus2+ppol+log_perc_OG,data =tpad2 )# balance asignación aleatoria Grupo A vs D
bal2 <- lm(TIPO2~factor(P40)+P41+educ+jus2+ppol+log_perc_OG,data =tpbd2 )# balance asignación aleatoria Grupo B vs D
bal3 <- lm(TIPO2~factor(P40)+P41+educ+jus2+ppol+log_perc_OG,data =tpcd2 )# balance asignación aleatoria Grupo C vs D

screenreg(l = list(bal1,bal2,bal3))
notabal <- c("\\parbox{.61\\linewidth}{\\vspace{2pt} Errores estándar entre paréntesis \\\\ 
          $^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$. \\\\
          \\textbf{\\textit{Nota}}: }")

coef <- c("(Intercepto)",
  "Sexo (ref: Mujer)",
  "Edad",
  "Educación",
  "Creencia Mundo Justo",
  "Centro",
  "Derecha",
  "Ninguno",
  "No sabe",
  "Desigualdad percibida (Log)"
  )
# texreg(list(bal1,bal2,bal3),
#        custom.model.names = c("Modelo 1", "Modelo 2", "Modelo 3"),
#        custom.coef.names = coef,
#           groups = list("\\textbf{Posición Política (ref: Izquierda)}" = 6:9),
#        caption = "Balance de la asignación aleatoria al grupo tratamiento",
#   caption.above = TRUE,
#   label = "tab:balance",
#   no.margin = T,
#   booktabs = TRUE,
#   dcolumn = TRUE,
#   single.row = FALSE,
#   bold = FALSE,
#   digits = 2,
#   leading.zero = TRUE,
#   use.packages = FALSE,
#   float.pos = "H",
#   scalebox = 0.75,
#   include.rs = FALSE,
#   include.rmse = FALSE,
#   custom.note = notabal,
#   file = "C:/Users/JC/Dropbox/Investigacion-Trump/paper/Resultados/tables/anexo_balance.tex")


```

```{r Comparacion de grupos}
e1ab03 <- lm(log_reco~factor(TIPO2), data = tpab2) #Grupo A vs B | Log(máximo/mínimo)
e1ac03 <- lm(log_reco~factor(TIPO2), data = tpac2) #Grupo A vs C | Log(máximo/mínimo)
e2bc03 <- lm(log_reco~factor(TIPO2), data = tpbc2) #Grupo B vs C | Log(máximo/mínimo)

```


```{r percepcion desigualdad ~ treatment}
pdesi1 <- lm(pdesi~factor(TIPO2)+ppol+log_perc_OG, data = tpad2) #Grupo A vs D | Dif ingreso son demasiado grandes + cov
pdesi2 <- lm(pdesi~factor(TIPO2)+ppol+log_perc_OG, data = tpbd2) #Grupo B vs D | Dif ingreso son demasiado grandes + cov
pdesi3 <- lm(pdesi~factor(TIPO2)+ppol+log_perc_OG, data = tpcd2) #Grupo C vs D | Dif ingreso son demasiado grandes + cov

```


```{r Modelos Desigualdad~Tratamientos+Covariables}
tpad2$TIPO2 <- factor(tpad2$TIPO2)
tpbd2$TIPO2 <- factor(tpbd2$TIPO2)
tpcd2$TIPO2 <- factor(tpcd2$TIPO2)
tpad2$educ  <- factor(tpad2$educ)
tpbd2$educ  <- factor(tpbd2$educ)
tpcd2$educ  <- factor(tpcd2$educ)
tpad2$educ  <- as.numeric(tpad2$educ)
tpbd2$educ  <- as.numeric(tpbd2$educ)
tpcd2$educ  <- as.numeric(tpcd2$educ)

e1ad04 <- lm(log_reco_OG~TIPO2, data = tpad2) #Grupo A vs D | Log(Gerente/obrero)
e1bd04 <- lm(log_reco_OG~TIPO2, data = tpbd2) #Grupo B vs D | Log(Gerente/obrero)
e2cd04 <- lm(log_reco_OG~TIPO2, data = tpcd2) #Grupo C vs D | Log(Gerente/obrero)

logOGcov1 <- lm(log_reco_OG~TIPO2+jus2+ppol+log_perc_OG+educ, data = tpad2) #Grupo A vs D 
logOGcov2 <- lm(log_reco_OG~TIPO2+jus2+ppol+log_perc_OG+educ, data = tpbd2) #Grupo B vs D 
logOGcov3 <- lm(log_reco_OG~TIPO2+jus2+ppol+log_perc_OG+educ, data = tpcd2) #Grupo C vs D 

screenreg(l = list(e1ad04,logOGcov1,e1bd04,logOGcov2,e2cd04,logOGcov3))

logOGcov4 <- lm(log_reco_OG~treat+jus2+ppol+log_perc_OG+educ, data = st) #Grupo simultáneo | Log(Gerente/obrero) + cov
```

```{r HC2}
library(sandwich) #HC2
library(lmtest) #coeftest

#---Test según cada Tratamiento Log(Gerente/obrero) con HC2--------------------
e1ad04HC2 <- coeftest(e1ad04   , vcov.= vcovHC(logOGcov1, "HC2"))#Grupo A vs D | Log(Gerente/obrero) sin cov(HC2)
e1bd04HC2 <- coeftest(e1bd04   , vcov.= vcovHC(logOGcov2, "HC2"))#Grupo B vs D | Log(Gerente/obrero) sin cov(HC2)
e2cd04HC2 <- coeftest(e2cd04   , vcov.= vcovHC(logOGcov3, "HC2"))#Grupo C vs D | Log(Gerente/obrero) sin cov(HC2)
logOGhc2a <- coeftest(logOGcov1, vcov.= vcovHC(logOGcov1, "HC2"))#Grupo A vs D | Log(Gerente/obrero) + cov (HC2)
logOGhc2b <- coeftest(logOGcov2, vcov.= vcovHC(logOGcov2, "HC2"))#Grupo B vs D | Log(Gerente/obrero) + cov (HC2)
logOGhc2c <- coeftest(logOGcov3, vcov.= vcovHC(logOGcov3, "HC2"))#Grupo C vs D | Log(Gerente/obrero) + cov (HC2)

#---Test simultáneo Log(Gerente/obrero) con HC2--------------------
logOGhc2 <- coeftest(logOGcov1, vcov.= vcovHC(logOGcov1, "HC2"))
logOGhc2[,1] #coef
logOGhc2[,2] #SE
logOGhc2[,3] #tvalue
logOGhc2[,4] #pvalue
nobs(logOGcov2)
# EL SE HC2 es consistente en muestras finitas e infinitas. Además, no asume ni homoscedasticidad ni linealidad.
```

```{r HC2-objetos-texreg}

extract.lmHC2 <- function(model) {
  s <- summary(model)
  hc2 <- coeftest(model, vcov.= vcovHC(model, "HC2"))
  names <- rownames(s$coef)
  co <- s$coef[, 1]
  se <- hc2[,2] #SE
  pval <- hc2[, 4]
  rs <- s$r.squared
  adj <- s$adj.r.squared
  n <- nobs(model)
  gof <- c(rs, adj, n)
  
gof.names <- c("R$^2$", "Adj.\\ R$^2$", "Num.\\ obs.")

   tr <- createTexreg(
       coef.names = names,
       coef = co,
       se = se,
       pvalues = pval,
       gof.names = gof.names,
       gof = gof)
   return(tr)
}
test <- createTexreg
m0a <- extract.lmHC2(e1ad04   ) #condición A con robust SE sin covariables
m0b <- extract.lmHC2(e1bd04   ) #condición B con robust SE sin covariables
m0c <- extract.lmHC2(e2cd04   ) #condición C con robust SE sin covariables
ac  <- extract.lmHC2(logOGcov1) #condición A con robust SE con covariables
bc  <- extract.lmHC2(logOGcov2) #condición B con robust SE con covariables
cc  <- extract.lmHC2(logOGcov3) #condición C con robust SE con covariables
htmlreg(l = c(m0a,ac,m0b,bc,m0c,cc)) #Modelos con robust SE
screenreg(l = list(e1ad04,logOGcov1,e1bd04,logOGcov2,e2cd04,logOGcov3))

```

```{r TABLA: Modelos Log(gerente/obrero)+controles, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(texreg)
texreg(list(e1ad04,logOGcov1,e1bd04,logOGcov2,e2cd04,logOGcov3),
                custom.model.names = c("Modelo 1", "Modelo 2", "Modelo 3","Modelo 4", "Modelo 5", "Modelo 6"),
                caption = "Log(Gerente/Obrero)",
                custom.coef.names = c("Intercepto","Tratamiento","Creencia Mundo Justo",
                                      "Centro", "Derecha", "Ninguno", "No sabe",
                                      "Desigualdad percibida (Log)","Educación"),
                caption.above = TRUE,
                reorder.coef = c(2:9,1),
       label = "tab:logcov",no.margin = T,
       booktabs = TRUE,
       dcolumn = TRUE,
       single.row = FALSE,
       bold = FALSE,
       digits = 2,
       leading.zero = TRUE,
       use.packages = FALSE,
       float.pos = "H",
       scalebox = 0.75,
       include.rs = FALSE,
       include.rmse = FALSE)
```

```{r TABLA: Modelos HC2, message=FALSE, warning=FALSE, , echo=FALSE, results='asis'}
notaA <- c("\\parbox{.61\\linewidth}{\\vspace{2pt} Errores estándar robustos entre paréntesis \\\\ 
          $^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$. \\\\
          \\textbf{\\textit{Nota}}: La variable dependiente  Desigualdad recomendada fue estandarizada a puntajes $z$ ($\\mu$=0, $\\sigma$=1) }")

notaB <- c("Errores estándar robustos entre parentesis <br>
           ***p&lt;0.001  **p&lt;0.01  *p&lt;0.05")

htmlreg(l = c(m0a,ac,m0b,bc,m0c,cc),
       custom.model.names = c("Modelo 1", "Modelo 2", "Modelo 3","Modelo 4", "Modelo 5", "Modelo 6"),
       custom.coef.names = c("Intercepto","Tratamiento","Creencia Mundo Justo",
                                      "Centro", "Derecha", "Ninguno", "No sabe",
                                      "Desigualdad percibida (Log)", "Educación"),
       reorder.coef = c(2:9,1),
       caption = "",
       label = "tab:logcov",
       no.margin = T,
       booktabs = TRUE,
       dcolumn = TRUE,
       single.row = FALSE,
       bold = FALSE,
       digits = 2,
       leading.zero = TRUE,
       use.packages = FALSE,
       float.pos = "H",
       scalebox = 0.75,
       include.rs = FALSE,
       include.rmse = FALSE,
       custom.note = notaB,
       file = here("tables","tabla1.xls")) 
```

```{terminal}
set PATH=%PATH%;C:\Program Files\stencila
cd C:\Users\JC\Dropbox\papers\Investigacion-Trump\Codigo-variables\Code-Stella-Trump\tables
stencila convert tabla1.ods tabla1.md

```


# Anexos

```{r Escala Creencia mundo justo}
#----correlacion----
just <- st %>% select(JW1,JW2,JW3,JW4,JW5)
corrplot(cor(just,use = "pairwise.complete.obs"),type = "lower")
?cor2latex()

cor2latex(just,use = "pairwise", method="pearson", adjust="holm",stars=TRUE,
       digits=2,rowlabels=TRUE,lower=TRUE,apa=TRUE,short.names=TRUE,
     font.size ="scriptsize", heading="A correlation table from the psych package in R.",
      caption="cor2latex",label="default",silent=FALSE,file=NULL,append=FALSE,cut=0,big=0)


#---EFA----
sjt.itemanalysis(just)

KMO(just) # Overall MSA =  0.68
cortest.bartlett(just) #Chi2= 489.6131 , p =0.00
plot(scree(just)) #Criterio codo= 1 factor

efa <- fa(just, nfactors = 1, fm = "ml", rotate = "oblimin")
fa.diagram(efa)
fa2latex(f = efa,
         rowlabels = TRUE,
         heading = NULL,
         caption = "Análisis Factorial Exploratorio para escala Creencia en un Mundo Justo",
         label = "efa_bwj",digits = 3, 
         font.size = "normalsize",
         apa = TRUE,
         file = "C:/Users/JC/Dropbox/Investigacion-Trump/paper/Resultados/tables/efa_bjw.tex")

# ML1 = Factor 1 extraído con método de máxima verosimilitud
# h2 = comunalidad
# u2 = unicidad
# com = complejidad de las cargas factoriales para la variable

#---CFA----
bjw <- 'just=~JW2+JW3+JW4+JW5'
fit <- cfa(model = bjw,
           data = st,
           ordered = c("JW2","JW3","JW4","JW5"))

summary(fit, standardized=TRUE)
fitmeasures(fit, fit.measures = c("chisq","pvalue","df","cfi","rmsea"))
```

```{r analisis factorial}
cor1 <-st %>%  select(log_perc_OG,log_reco_OG, just)
cor2 <- cor(cor1,use = "pairwise.complete.obs")
sjt.corr(cor1)
psych::cor2latex(cor1,stars = TRUE)
```

```{r zscore-log_anexos}
e1ad05 <- lm(zlog~factor(TIPO2), data = tpad2) #Grupo A vs D | Log(Gerente/obrero)
e1bd05 <- lm(zlog~factor(TIPO2), data = tpbd2) #Grupo B vs D | Log(Gerente/obrero)
e2cd05 <- lm(zlog~factor(TIPO2), data = tpcd2) #Grupo C vs D | Log(Gerente/obrero)
logOGcov1a <- lm(zlog~factor(TIPO2)+jus2+ppol+log_perc_OG+educ, data = tpad2) #Grupo A vs D | Log(Gerente/obrero) + cov
logOGcov2b <- lm(zlog~factor(TIPO2)+jus2+ppol+log_perc_OG+educ, data = tpbd2) #Grupo B vs D | Log(Gerente/obrero) + cov
logOGcov3c <- lm(zlog~factor(TIPO2)+jus2+ppol+log_perc_OG+educ, data = tpcd2) #Grupo C vs D | Log(Gerente/obrero) + cov

nota <- c("\\parbox{.61\\linewidth}{\\vspace{2pt} Errores estándar entre paréntesis \\\\ 
          $^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$. \\\\
          \\textbf{\\textit{Nota}}: La variable dependiente  Desigualdad recomendada fue estandarizada a puntajes $z$ ($\\mu$=0, $\\sigma$=1) }")
notab <- c("Errores estándar entre paréntesis <br>
          ***p&lt;0.001  **p&lt;0.01  *p&lt;0.05 <br>
          _**Nota**_ La variable dependienteDesigualdad recomendada fue estandarizada a puntajes $z$ ($\\mu$=0, $\\sigma$=1)}")

#--- EN LATEX-------------------------------------------------#
texreg(
  list(logOGcov1a, logOGcov2b, logOGcov3c),
  custom.model.names = c("Modelo 1", "Modelo 2", "Modelo 3"),
  custom.coef.names = c(
    "Intercepto",
    "Tratamiento",
    "Creencia Mundo Justo",
    "Centro",
    "Derecha",
    "Ninguno",
    "No sabe",
    "Desigualdad percibida (Log)",
    "Educación"
  ), 
  caption = "Modelos de regresi\\'on para Desigualdad recomendada en unidades de desviación estándar $z$",
  caption.above = TRUE,
  reorder.coef = c(2:9, 1),
  label = "tab:logcov_z",
  no.margin = T,
  booktabs = TRUE,
  dcolumn = TRUE,
  single.row = FALSE,
  bold = FALSE,
  digits = 2,
  leading.zero = TRUE,
  use.packages = FALSE,
  float.pos = "H",
  scalebox = 0.75,
  include.rs = FALSE,
  include.rmse = FALSE,
  custom.note = nota)

#--- EN HTML-------------------------------------------------#
htmlreg(
  list(logOGcov1a, logOGcov2b, logOGcov3c),
  custom.model.names = c("Modelo 1", "Modelo 2", "Modelo 3"),
  custom.coef.names = c(
    "Intercepto",
    "Tratamiento",
    "Creencia Mundo Justo",
    "Centro",
    "Derecha",
    "Ninguno",
    "No sabe",
    "Desigualdad percibida (Log)",
    "Educación"
  ), 
  caption = "",
  caption.above = TRUE,
  reorder.coef = c(2:9, 1),
  label = "tab:logcov_z",
  no.margin = FALSE,
  booktabs = TRUE,
  dcolumn = TRUE,
  single.row = FALSE,
  bold = FALSE,
  digits = 2,
  leading.zero = TRUE,
  use.packages = FALSE,
  float.pos = "H",
  scalebox = 0.75,
  include.rs = FALSE,
  include.rmse = FALSE,
  custom.note = notab,
  file = here("tables","tabla_zval.xls"))


```

```{r}
gap<- 10171496/228640 #Basado en CASEN 2011************ #44.48695 

mean(st$perc_OG,na.rm = TRUE) #37.97615

st %>% group_by(treat) %>% summarise(mean(perc_OG, na.rm = TRUE))
st %>% group_by(treat) %>% summarise(mean(reco_OG, na.rm = TRUE))


prop.table(table(tpad2$perc_OG>=gap)) # % que dice que la brecha es mayor a lo que realmente es
prop.table(table(tpbd2$perc_OG>=gap))
prop.table(table(tpcd2$perc_OG>=gap))
prop.table(table(st$perc_OG>=gap)) # 0.8189533 == es menor | 93 en Trump
                                   # 0.1810467 == es mayor
```

```{r ENACOES}
enacoes <- read_dta("C:/Users/JC/Google Drive/Bases de Datos/COES/ENACOES_2014/ENACOES_2014_V4.dta") 

data1 <- enacoes %>% select(B7_A, B7_B, B6_A, B6_B)

data1$B6_A <-  recode(data1$B6_A,recodes = "99=NA") #Gerente de una gran empresa
data1$B6_B <-  recode(data1$B6_B,recodes = "99=NA") #Obrero no calificado de una fábrica

data1$per_gerente <- data1$B6_A
data1$per_obrero  <- data1$B6_B
data1$per_OG <- (data1$per_gerente/data1$per_obrero)

mean(data1$per_gerente, na.rm = TRUE,trim = 0.1)
freq <- data1 %>% group_by(per_OG) %>% summarise(n=n())

mean(data1$per_OG,na.rm = TRUE) #percepción de salario Gerente/obrero
mean(data1$per_OG,na.rm = TRUE, trim = 0.1) # media recortada (10% extremos)


data1$B7_A <-  recode(data1$B7_A,recodes = "99=NA") #Gerente de una gran empresa
data1$B7_B <-  recode(data1$B7_B,recodes = "99=NA") #Obrero no calificado de una fábrica

data1$rec_gerente <- data1$B7_A
data1$rec_obrero  <- data1$B7_B

data1$rec_OG <- (data1$rec_gerente/data1$rec_obrero)

mean(data1$rec_OG,na.rm = TRUE) #23.58908

sjp.frq(data1$per_OG, type = "h", show.mean = TRUE, show.mean.val = TRUE,
        normal.curve = TRUE, show.sd = TRUE, normal.curve.color = "blue")
```

